/**
 * Lot intake. One row = one order line = one lot. The lot number, order id,
 * sequence, expiry, and BUD are auto-generated by the lotIdGenerator service.
 */
const express = require("express");
const prisma = require("../../prisma/client");
const { requirePermission } = require("../../middleware/auth");
const gen = require("../../services/lotIdGenerator");

const router = express.Router();
const READ = requirePermission("LOTS", "READ");
const CREATE = requirePermission("LOTS", "CREATE");
const UPDATE = requirePermission("LOTS", "UPDATE");

const lotInclude = {
  company: true,
  supplier: true,
  peptide: true,
  strength: true,
  coas: { select: { id: true, coaNumber: true, status: true } },
};

router.get("/lots", READ, async (req, res) => {
  const { companyId, status, peptideId, page = 1, limit = 50 } = req.query;
  const where = {};
  if (companyId) where.companyId = companyId;
  if (status) where.status = status;
  if (peptideId) where.peptideId = peptideId;
  const take = parseInt(limit);
  const skip = (parseInt(page) - 1) * take;
  const [rows, total] = await Promise.all([
    prisma.lot.findMany({ where, include: lotInclude, orderBy: { createdAt: "desc" }, skip, take }),
    prisma.lot.count({ where }),
  ]);
  res.json({ success: true, data: { data: rows, pagination: { total, page: parseInt(page), limit: take, totalPages: Math.ceil(total / take) } } });
});

router.get("/lots/:id", READ, async (req, res) => {
  const row = await prisma.lot.findUnique({ where: { id: req.params.id }, include: { ...lotInclude, coas: { include: { lab: true, tests: true } } } });
  if (!row) return res.status(404).json({ success: false, error: "Lot not found" });
  res.json({ success: true, data: row });
});

// Live preview of the generated values (for the intake form, no write)
router.post("/lots/preview", READ, async (req, res) => {
  try {
    const { peptideId, peptideStrengthId, mfgDate, supplierId, orderDate, seq } = req.body;
    const [peptide, strength, supplier, patterns] = await Promise.all([
      prisma.peptide.findUnique({ where: { id: peptideId } }),
      prisma.peptideStrength.findUnique({ where: { id: peptideStrengthId } }),
      prisma.supplier.findUnique({ where: { id: supplierId } }),
      gen.getPatterns(),
    ]);
    if (!peptide || !strength || !supplier) return res.status(400).json({ success: false, error: "Missing peptide, strength, or supplier" });
    const seqVal = seq || (await gen.nextSequence({ peptideId, peptideStrengthId, mfgDate }));
    const shelf = peptide.shelfLifeMonths || gen.DEFAULT_SHELF_LIFE_MONTHS;
    res.json({
      success: true,
      data: {
        lotNumber: gen.buildLotNumber(patterns.LOT_NUMBER, { peptideCode: peptide.code, strengthCode: strength.code, mfgDate, seq: seqVal }),
        procurementOrderId: gen.buildOrderId(patterns.ORDER_ID, { supplierCode: supplier.code, orderDate }),
        seq: seqVal,
        expirationDate: gen.calcExpiration(mfgDate, shelf),
        bud: gen.budText(shelf),
      },
    });
  } catch (e) {
    res.status(400).json({ success: false, error: e.message });
  }
});

router.post("/lots", CREATE, async (req, res) => {
  try {
    const { companyId, supplierId, peptideId, peptideStrengthId, quantity, mfgDate, orderDate, receivedDate, storage, status, notes, seq } = req.body;
    const result = await prisma.$transaction(async (tx) => {
      const [peptide, strength, supplier, patterns] = await Promise.all([
        tx.peptide.findUnique({ where: { id: peptideId } }),
        tx.peptideStrength.findUnique({ where: { id: peptideStrengthId } }),
        tx.supplier.findUnique({ where: { id: supplierId } }),
        gen.getPatterns(),
      ]);
      if (!peptide || !strength || !supplier) throw new Error("Invalid peptide, strength, or supplier");
      const seqVal = seq || (await gen.nextSequence({ peptideId, peptideStrengthId, mfgDate }, tx));
      const shelf = peptide.shelfLifeMonths || gen.DEFAULT_SHELF_LIFE_MONTHS;
      return tx.lot.create({
        data: {
          lotNumber: gen.buildLotNumber(patterns.LOT_NUMBER, { peptideCode: peptide.code, strengthCode: strength.code, mfgDate, seq: seqVal }),
          companyId,
          procurementOrderId: gen.buildOrderId(patterns.ORDER_ID, { supplierCode: supplier.code, orderDate }),
          orderDate: new Date(orderDate),
          supplierId,
          peptideId,
          peptideStrengthId,
          quantity: parseInt(quantity),
          mfgDate: new Date(mfgDate),
          seq: seqVal,
          expirationDate: gen.calcExpiration(mfgDate, shelf),
          bud: gen.budText(shelf),
          receivedDate: receivedDate ? new Date(receivedDate) : null,
          storage: storage || undefined,
          status: status || undefined,
          notes: notes || null,
        },
        include: lotInclude,
      });
    });
    res.json({ success: true, data: result });
  } catch (e) {
    res.status(e.code === "P2002" ? 409 : 400).json({ success: false, error: e.code === "P2002" ? "A lot with this number already exists (sequence collision)" : e.message });
  }
});

router.patch("/lots/:id", UPDATE, async (req, res) => {
  try {
    const allowed = ["quantity", "receivedDate", "storage", "status", "notes"];
    const data = {};
    for (const k of allowed) {
      if (k in req.body) {
        if (k === "receivedDate") data[k] = req.body[k] ? new Date(req.body[k]) : null;
        else if (k === "quantity") data[k] = parseInt(req.body[k]);
        else data[k] = req.body[k];
      }
    }
    const row = await prisma.lot.update({ where: { id: req.params.id }, data, include: lotInclude });
    res.json({ success: true, data: row });
  } catch (e) {
    res.status(400).json({ success: false, error: e.message });
  }
});

module.exports = router;
